walkmod-override-plugin
=======================
Raquel Pau <raquelpau@gmail.com>

This is a walkmod plugin to add the override annotation in Java methods whenever it is necessary 
(when a given class implements an interface or defines a method that belongs to its superclass). 

== Example
Let's see an example. From this code, which is a class with its typical `toString` implementation. 

```java
package example;

public class Foo{
 
  public String toString(){
    ...
  }
}
```

It is transformed to :
```java
package example;

public class Foo{

  @Override
  public String toString(){
    ...
  }
}
```

== Usage

Add the transformation `override` and your project build tool name (maven or gradle) as a configuration provider into your `walkmod.xml` .

```XML
<!DOCTYPE walkmod PUBLIC "-//WALKMOD//DTD"  "http://www.walkmod.com/dtd/walkmod-1.1.dtd" >
<walkmod>
  <conf-providers>
    <conf-provider type="maven"></conf-provider>
  </conf-providers>
  <chain name="main-chain">	
    <transformation type="override"/>
  </chain>	
</walkmod>
```

You can apply walkmod-override-plugin via walkmod. 

  $ walkmod apply

Or, you can also check which would be the modified classes typing:

  $ walkmod check


== Contributing

If you want to hack on this, fork it, improve it and send me a pull request.

To get started using it, just clone it and call mvn install. 


